#!/bin/bash

clear

# Get the current version and password
read -p "Assignment number: " assignment
read -p "Pyrite password: " password

folder="Ray_Ryan.assignment-$assignment"

# Build the assignment
./deploy $assignment

sshpass -p $password scp submissions/$folder.tar.gz ryanr@pyrite.cs.iastate.edu:~

# Upload and unpack the assignment
sshpass -p $password ssh ryanr@pyrite.cs.iastate.edu "\
    tar xfzv $folder.tar.gz; \
    rm $folder.tar.gz; \
    cd $folder; \
    rm -rf ~/.rlg327; \
    echo \"------------------------------------------------------------------------------------\"; \
    make && echo \"------------------------------------------------------------------------------------\" && make test; \
    cd ..; \
    rm -r $folder;"