#!/bin/bash

# Get the assignment number
if [ -z "$1" ]; then
	read -p "Assignment number: " assignment
else
	assignment=$1
fi

# Remove any binaries
make clean -s

# Make the change log
git log > CHANGELOG

# Create a copy with the correct name
cd ..
cp -R  /media/sf_cs327/ /tmp/Ray_Ryan.assignment-$assignment

# Remove any empty folders
cd /tmp/Ray_Ryan.assignment-$assignment
find . -type d -empty -delete
cd ..

# Make the tar ball
tar cfz Ray_Ryan.assignment-$assignment.tar.gz Ray_Ryan.assignment-$assignment \
	--exclude=".*" --exclude="deploy" --exclude="*.tar.gz" --exclude="submissions"

# Move the tar ball to the workspace
cp /tmp/Ray_Ryan.assignment-$assignment.tar.gz  /media/sf_cs327/submissions/Ray_Ryan.assignment-$assignment.tar.gz

# Clean up
rm -rf Ray_Ryan.assignment-$assignment
rm -rf Ray_Ryan.assignment-$assignment.tar.gz

# Tell the user that we are done
echo "Build complete"
