#!/bin/bash

# Make sure we are in the right place
cd /workspace

# Get the assignment number
if [ -z "$1" ]; then
	read -p "Assignment number: " assignment
else
	assignment=$1
fi

# Remove any binaries
make clean -s

# Make the change log
git log > CHANGELOG

# Create a copy with the correct name
cd ..
cp -R /workspace /tmp/Ray_Ryan.assignment-$assignment

# Remove any empty folders
cd /tmp/Ray_Ryan.assignment-$assignment
find . -type d -empty -delete
cd ..

# Make the tar ball
tar cfz Ray_Ryan.assignment-$assignment.tar.gz Ray_Ryan.assignment-$assignment \
	--exclude=".*" --exclude="deploy*" --exclude="Vagrantfile" --exclude="*.tar.gz"

# Move the tar ball to the workspace
cp /tmp/Ray_Ryan.assignment-$assignment.tar.gz /workspace/Ray_Ryan.assignment-$assignment.tar.gz

# Clean up
rm -rf Ray_Ryan.assignment-$assignment
rm -rf Ray_Ryan.assignment-$assignment.tar.gz

# Tell the user that we are done
echo "Build complete"
