#!/bin/bash

# test a number of queens
queen() {
	# tell the user what were doing
	echo -n "[ .. ]: $1 queens"

	# recompile for this many queens
	gcc src/8queens.c -DSIZE=$1 -o build/8queens
	# count the number of results
	count=$(build/8queens $1 | wc -l)

	# print the result
	if [ "$count" = "$2" ]; then
		echo -e "\r[ OK ]: $1 queens"
	else
		echo -e "\r[FAIL]: $1 ($count != $2)"
		exit 1
	fi
}

# test for 5, 6, 7, and 8 queens
queen 5 10
queen 6 4
queen 7 40
queen 8 92
