Remove-Item -Recurse -Force CMakeFiles 2> $null
Remove-Item -Recurse -Force Debug 2> $null
Remove-Item -Recurse -Force ALL_BUILD.vcxproj 2> $null
Remove-Item -Recurse -Force ALL_BUILD.vcxproj.filters 2> $null
Remove-Item -Recurse -Force cmake_install.cmake 2> $null
Remove-Item -Recurse -Force CMakeCache.txt 2> $null
Remove-Item -Recurse -Force rlg.sln 2> $null
Remove-Item -Recurse -Force rlg.vcxproj 2> $null
Remove-Item -Recurse -Force rlg.vcxproj.filters 2> $null
Remove-Item -Recurse -Force ZERO_CHECK.vcxproj 2> $null
Remove-Item -Recurse -Force ZERO_CHECK.vcxproj.filters 2> $null
Remove-Item -Recurse -Force Win32 2> $null
Remove-Item -Recurse -Force rlg 2> $null
Remove-Item -Recurse -Force Makefile 2> $null
Remove-Item -Recurse -Force rlg.dir 2> $null
Remove-Item -Recurse -Force build 2> $null
Remove-Item -Recurse -Force ALL_BUILD.vcxproj.user 2> $null
Remove-Item -Recurse -Force rlg.vcxproj.user 2> $null
Remove-Item -Recurse -Force PDCurses.vcxproj 2> $null
Remove-Item -Recurse -Force PDCurses.vcxproj.filters 2> $null
Remove-Item -Recurse -Force PDCurses.dir 2> $null
Remove-Item -Recurse -Force .vs 2> $null
