Remove-Item -Recurse -Force CMakeFiles
Remove-Item -Recurse -Force Debug
Remove-Item -Recurse -Force ALL_BUILD.vcxproj
Remove-Item -Recurse -Force ALL_BUILD.vcxproj.filters
Remove-Item -Recurse -Force cmake_install.cmake
Remove-Item -Recurse -Force CMakeCache.txt
Remove-Item -Recurse -Force rlg.sln
Remove-Item -Recurse -Force rlg.vcxproj
Remove-Item -Recurse -Force rlg.vcxproj.filters
Remove-Item -Recurse -Force ZERO_CHECK.vcxproj
Remove-Item -Recurse -Force ZERO_CHECK.vcxproj.filters
Remove-Item -Recurse -Force Win32
Remove-Item -Recurse -Force rlg
Remove-Item -Recurse -Force Makefile
Remove-Item -Recurse -Force rlg.dir
Remove-Item -Recurse -Force build
Remove-Item -Recurse -Force ALL_BUILD.vcxproj.user
Remove-Item -Recurse -Force rlg.vcxproj.user
